name: quick_shop_admin
description: "Quick Shop Admin App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.1.0
  intl: ^0.18.1
  url_launcher: ^6.1.12
  connectivity_plus: ^6.1.0
  lottie: ^3.1.3
  shimmer: ^3.0.0
  logger: ^2.0.1
  cached_network_image: ^3.4.1

  # Web Packages
  url_strategy: ^0.3.0
  data_table_2: ^2.5.16
  fl_chart: ^0.69.2

  # Icons
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8

  # State Management
  get: ^4.6.5
  get_storage: ^2.1.1

  # Firebase
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  google_sign_in: ^6.2.2
  firebase_storage: ^12.3.6


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.14.1"


flutter:
  uses-material-design: true

  #------------------local_assets-------------------#
  assets:
    - assets/logos/
    # - assets/images/on_boarding_images/
    - assets/images/animations/
    # - assets/images/banners/
    # - assets/images/products/
    - assets/images/content/
    # - assets/images/reviews/
    # - assets/icons/categories/
    # - assets/icons/brands/
    # - assets/icons/payment_methods/


  #------------------Local Fonts-------------------#
  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Light.ttf
          weight: 300
        - asset: assets/fonts/Urbanist-Regular.ttf
          weight: 400
        - asset: assets/fonts/Urbanist-Italic.ttf
          style: italic
        - asset: assets/fonts/Urbanist-Medium.ttf
          weight: 500
        - asset: assets/fonts/Urbanist-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Urbanist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Urbanist-Bold.ttf
          weight: 800
        - asset: assets/fonts/Urbanist-ExtraBold.ttf
          weight: 900

#------------------APP Icon Generation-------------------#
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logos/quick_shop_app.png"
  min_sdk_android: 34
  web:
    generate: true
    image_path: "assets/logos/quick_shop_app.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  macos:
    generate: true
    image_path: "assets/logos/quick_shop_app.png"
